config/routes.rb
Fiftyfivelproject::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/apply',   to: 'static_pages#apply',   via: 'get'

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  before_create :create_remember_token
	has_secure_password 

	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, 
										uniqueness: { case_sensitive: false } 
	validates :password, length: { minimum: 6 } 

	def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

	  def create_remember_token
	  	self.remember_token = User.encrypt(User.new_remember_token)
	  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

	def create
	  user = User.find_by(email: params[:session][:email].downcase)
	  if user && user.authenticate(params[:session][:password])
	    sign_in user
      redirect_to user
	  else
	    flash.now[:error] = 'Invalid email/password combination' # Not quite right!
      render 'new'
	  end
	end

  def destroy
  	sign_out 
  	redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
  end

  def about
  end

  def apply
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end

  def create 
  	@user = User.new(user_params)	 
  	if @user.save
      sign_in @user
  		flash[:success] = "You've created a new user"
  		redirect_to @user
  	else 
  		render 'new'
  	end
  end

  private 

  	def user_params
  		params.require(:user).permit(:name, :email, :password, :password_confirmation)
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the full title on a per-page basis.  
	def full_title(page_title)
		base_title = "55L Project"
		if page_title.empty?
			base_title
		else 
			"#{page_title} | #{base_title}"
		end
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
	  remember_token = User.new_remember_token
	  cookies.permanent[:remember_token] = remember_token
	  user.update_attribute(:remember_token, User.encrypt(remember_token))
	  self.current_user = user
	end

	def signed_in?
  	!current_user.nil?
  end

	def current_user=(user)
		@current_user = user 
	end 

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def sign_out
	  self.current_user = nil
	  cookies.delete(:remember_token)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

	# Returns the Gravatar (http://gravatar.com/) for the given user.
	def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="footer"> 
	<small>
		&copy; 55L Project  
	</small>
</footer>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "55L", root_path, class: 'navbar-brand' %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home",  root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Apply", apply_path %></li>
      <% if signed_in? %> 
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Settings", '#' %></li>
            <li class="divider"></li>
            <li>
              <%= link_to "Sign out", signout_path, method: "delete" %>
            </li>
          </ul>
        </li>
      <% else %> 
        <li><%= link_to "Sign in", signin_path %></li>
      <% end %> 
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--
                                                ~ (@)  ~~~---_
                                               {     `-_~,,,,,,)
                                               {    (_  ',
                                                ~    . = _',
                                                 ~    '.  =-'
                                                   ~     :
.                                                -~     ('');
'.                                         --~        \  \ ;
  '.-_                                   -~            \  \;      _-=,.
     -~- _                          -~                 {  '---- _'-=,.
       ~- _~-  _              _ -~                     ~---------=,.`
            ~-  ~~-----~~~~~~       .+++~~~~~~~~-__   /
                ~-   __            {   -     +   }   /
                         ~- ______{_    _ -=\ / /_ ~
                             :      ~--~    // /         ..-
                             :   / /      // /         ((
                             :  / /      {   `-------,. ))
                             :   /        ''=--------. }o
                .=._________,'  )                     ))
                )  _________ -''                     ~~
               / /  _ _
              (_.-.'O'-'.
 ____    ___                                      ____               ___      
/\  _`\ /\_ \                                    /\  _`\   __       /\_ \     
\ \ \/\_\//\ \      __   __  __     __   _ __    \ \ \L\_\/\_\  _ __\//\ \    
 \ \ \/_/_\ \ \   /'__`\/\ \/\ \  /'__`\/\`'__\   \ \ \L_L\/\ \/\`'__\\ \ \   
  \ \ \L\ \\_\ \_/\  __/\ \ \_/ |/\  __/\ \ \/     \ \ \/, \ \ \ \ \/  \_\ \_ 
   \ \____//\____\ \____\\ \___/ \ \____\\ \_\      \ \____/\ \_\ \_\  /\____\
    \/___/ \/____/\/____/ \/__/   \/____/ \/_/       \/___/  \/_/\/_/  \/____/
                                                                               
-->
<html>
  <head>
  	<!-- metas, make these dynamic and add favicon -->
  	<meta charset="utf-8">
  	<meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- make these dynamic and add favicon -->
    <meta name="description" content="The 55L Project is a loosely themed collection of short-form and hyper-focused travel guides written to give readers the starting knowledge they need to stop reading and start experiencing.">
    <meta name="keywords" content="55l, 55l project, 55lproject, 55lco, travel, travel guides, travel advice, travel expert, solo travel, backpacking, explore, travel tips, flashpacker, backpacker, independent travel, experience, world, expert" />
    <title><%= full_title(yield(:title)) %></title>

    <!-- OG, make these dynamic --> 
    <meta property="og:type"    content="website"/>
    <meta property="fb:page_id"   content="211699165670804" />
    <meta property="og:site_name"   content="55L" />
    <meta property="og:url"     content="http://www.55l.co" />
    <meta property="og:title"     content="55L Project" />    
    <meta property="og:image"     content="https://s3.amazonaws.com/fiftyfiveloriginal/images/logo_200x200.png" />
    <meta property="og:description" content="The 55L Project is a loosely themed collection of short-form and hyper-focused travel guides written to give readers the starting knowledge they need to stop reading and start experiencing." />

    <!-- CSS --> 
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    
    <!-- csrf --> 
  	<%= csrf_meta_tags %>

    <!-- Dat GA Stuff --> 
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-10352533-7', '55l.co');
      ga('send', 'pageview');
    </script>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %> 
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
    </div>
    <div class="container">    
      <%= yield %>
      <%= render 'layouts/footer' %> 
      <%= debug(params) if Rails.env.development? %> 
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About the Project') %>
<h1>The internet is a room full of strangers.</h1>
<p>
	<strong>We're a bar full of friends.</strong> Here's more about the project.
</p>

app/views/static_pages/apply.html.erb
<% provide(:title, 'Write for the Project') %>
<h1>Wanna publish with the project?</h1>
<p>
	We operate on an invite system. If you've got an idea and an itch to write, we encourage you to apply.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Make No Small Plans") %>
<div class="jumbotron">
	<h1>People make the best guide books.</h1>
	
	<h2>
	  Welcome. You said the magic words.
	</h2>

	<p>
		Soon, you'll be able to <em>get yours</em> or <em>be one</em>
	</p>

	<%= link_to "Create User", signup_path, class: "btn btn-large btn-primary" %> 
</div>

app/views/users/new.html.erb
<% provide(:title, 'Create User') %>
<h1>Create User</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages' %> 

		  <%= f.label :name %>
		  <%= f.text_field :name %>
		  
		  <%= f.label :email %>
		  <%= f.text_field :email %>
		  
		  <%= f.label :password %>
		  <%= f.password_field :password %>
		  
		  <%= f.label :password_confirmation, "Confirmation" %>
		  <%= f.password_field :password_confirmation %>
		  
		  <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
      	<%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>